version: '3'

services:
  #setup node using Dockerfile
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - mongo
  app2:
    container_name: docker-node-mongo-2
    restart: always
    build: .
    ports:
      - '8081:8080'
    links:
      - mongo
  # setup db
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - app
  #   ports:
  #     - '4000:4000'