version: '3'

services:
  nodeapp:
    image: todoapp
    ports:
      - 8080:8080
    deploy:
      replicas: 3
      restart_policy:
        max_attempts: 3
        condition: on-failure       
      update_config:
        parallelism: 3
        delay: 10s
    depends_on:
      - mongo
    environment:
      - DB_URL=mongodb://mongo/meanstacktutorials
    networks: 
      - balance 
  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks: 
      - balance
  
  proxy:
    image: balancer
    ports:
      - 80:80
    depends_on:
      - nodeapp
    deploy:
      placement:
        constraints: [node.role == manager]
    networks: 
      - balance

networks:
  balance:
    driver: overlay