version: '3'

services:
  #setup node using Dockerfile
  app:
    # container_name: docker-node-mongo
    # restart: alwayscd
    # build: .
    image: medullan/app
    ports:
      - '8080:8080'
    deploy:
      replicas: 3
      restart_policy:
        max_attempts: 3
        condition: on-failure
    depends_on:
      - mongo
    networks:
      - balance
  # setup db
  mongo:
    # container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - balance
  proxy:
    image: medullan/balancer
    ports: 
      - '9000:80'
    depends_on:
      - app
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - balance

networks: 
  balance:
    driver: overlay