version: '3'

services:
  #setup node using Dockerfile
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - mongo
  # setup db
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'